apiVersion: apps/v1
kind: Deployment
metadata:
  name: apidemo
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: apidemo
    spec:
      containers:
      - name: apidemo
        image: apidemo:v0.1
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: apidemo
spec:
  type: NodePort
  ports:
  - port: 80
  selector:
    app: apidemo